# Site settings
site:
  title: yarn
  author: Yarn
  email: my@email.com
  description: > # this means to ignore newlines until "baseurl:"
    Homepage of yarn, static site generator.
  keywords: "static site generator, static site, yarn, nodejs, javascript"
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "http://yarnjs.github.io/"

path:
  source:      ./
  destination: ./_site
  plugins:     ./_plugins
  themes:      ./_themes

# What is the current theme.
theme: 'default'

# If we should remove the compile destination folder before writing.
clean_destination: true

file:
  defaults:
    -
      scope:
         path: ./
      values:
        template: page
    -
      scope:
        path: ./docs/
      values:
        template: docs_page
        permalink: /docs/:title/
    -
      scope:
        path: ./_posts
      values:
        template: post
        permalink: /blog/:title/
  filters:
    metadata:
      draft: true
    future_date:
      key: date

collections:
  post:
    path: ./_posts
    template: index
    page_size: 6
    sort:
      key: date
      order: descending
    permalink:
      index: /blog/
      page:  /blog/page/:page/
  tag:
    template: tag
    page_size: 6
    metadata: tags
    sort:
      key: date
      order: descending
    permalink:
      index: /blog/tag/:metadata/
      page:  /blog/tag/:metadata/:page/

plugins:
  html-minifier:
    enabled: true
  excerpt:
    enabled: true
